from srModule.Model import Audio
import time
song0 = Audio.initFromFile("song/liangyu.mp3")
print(song0.getId(new=True))
print("get")
print(song0.fs,song0.channels)
a = time.time()
print(song0.getFingerprints())
print(len(song0.fingerprints))
print("use",time.time()-a)
print("down")
# a = time.time()
# song0.startInsertFingerprints()
#song0.insertFingerprints()
# print("use",time.time()-a)
# print("ok")
# a = time.time()
# print(song0.recognize())
# b = time.time()
# print(b-a)